import { pool } from "./db.js";
import bcrypt from "bcryptjs";

async function main() {
  // Tabele
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username TEXT UNIQUE NOT NULL,
      password_hash TEXT NOT NULL,
      role TEXT NOT NULL CHECK (role IN ('admin','user')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS employees (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      color TEXT,
      active BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS clients (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      full_name TEXT NOT NULL,
      phone TEXT,
      -- email celowo pomijamy (nie używasz maila)
      notes TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS appointments (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
      client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
      start_at TIMESTAMPTZ NOT NULL,
      end_at TIMESTAMPTZ NOT NULL,
      service_name TEXT NOT NULL,
      notes TEXT,
      created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    CREATE INDEX IF NOT EXISTS idx_appointments_time ON appointments(start_at, end_at);
    CREATE INDEX IF NOT EXISTS idx_appointments_employee ON appointments(employee_id);
    CREATE INDEX IF NOT EXISTS idx_appointments_client ON appointments(client_id);
  `);

  // Admin
  const adminRes = await pool.query("SELECT id FROM users WHERE username = $1", ["admin"]);
  if (adminRes.rowCount === 0) {
    const hash = bcrypt.hashSync("admin123", 10);
    await pool.query(
      "INSERT INTO users (username, password_hash, role) VALUES ($1,$2,$3)",
      ["admin", hash, "admin"]
    );
    console.log("✅ Created default admin: admin / admin123");
  } else {
    console.log("ℹ️ Admin already exists");
  }

  // Pracownicy demo
  const empRes = await pool.query("SELECT id FROM employees LIMIT 1");
  if (empRes.rowCount === 0) {
    await pool.query("INSERT INTO employees (name, color) VALUES ($1,$2)", ["Ala", "#7c3aed"]);
    await pool.query("INSERT INTO employees (name, color) VALUES ($1,$2)", ["Ola", "#0ea5e9"]);
    console.log("✅ Added sample employees");
  }

  console.log("✅ DB ready (Postgres)");
  process.exit(0);
}

main().catch((err) => {
  console.error("❌ init_pg failed", err);
  process.exit(1);
});
